server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  application:
    name: students

  datasource:
    url: ${SPRING_DATASOURCE_URL_LOCAL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-Name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-0-master.xml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none